sonar.organization=mindulmendul
sonar.projectKey=MindulMendul_haruhan
sonar.projectName=haruhan
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/content/cs/contents.json
sonar.coverage.exclusions=src/app/**,src/api/**,src/components/**,src/content/**,src/hooks/**,src/lib/supabase.ts,src/lib/theme.ts,src/**/*.test.ts,src/**/*.test.tsx
sonar.cpd.exclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
