sonar.organization=mindulmendul
sonar.projectKey=MindulMendul_haruhan
sonar.projectName=haruhan
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/entities/cs-topic/content/contents.json
sonar.coverage.exclusions=src/app/**,src/widgets/**,src/scripts/**,src/shared/ui/**,src/shared/api/**,src/shared/hooks/**,src/shared/lib/theme.ts,src/entities/**/ui/**,src/entities/**/model/**,src/entities/position/**,src/**/*.test.ts,src/**/*.test.tsx
sonar.cpd.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/entities/cs-topic/content/**,src/entities/position/content/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
